apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: my-redis
  name: my-redis
spec:
  selector:
    matchLabels:
      app: my-redis
  template:
    metadata:
      labels:
        app: my-redis
    spec:
      containers:
      - image: redis
        name: my-redis